# Points to the HFC config file
ontologyFile:       src/main/resources/ontology/drz.yml

# ########## COMPILE CONFIGURATION SETTINGS ##########
inputFile:          src/main/rudi/MissionKnowledge.rudi
outputDirectory:    src/main/gen-java
agentBase:          de.dfki.drz.mkm.KnowledgeManager
typeDef:            KnowledgeManager.rudi
checkTypes:         true
failOnError:        false
verbose:            false
rootPackage:        de.dfki.drz.mkm

nameToURI:
  Agent: <dial:Agent>
#nameToClass:
#  Date: de.dfki.drz.mkm.util.Date
#printErrors: false   # prints compile errors to terminal, true is the default
#visualise: true      # produces a graphical representation of the parsed
                      # rule files
                      # with type resolution information
#persistentVars: true # puts compiler into persistent variables mode: local
                      # variables in included rule files also keep their
                      # values during runtime

# ########## RUN CONFIGURATION SETTINGS ##########

NLG:
  de_DE:
    class: de.dfki.mlt.rudimant.agent.nlp.LanguageGenerator
    mapperProject: src/main/resources/grammars/cplanner/allrules-mapper
    generationProject: src/main/resources/grammars/cplanner/allrules
    #translateNumbers: true  # translates numbers to text internally, if, e.g., the TTS
                             # can not do it by itself
NLU:
  de_DE:
    class: de.dfki.mlt.rudimant.agent.nlp.SrgsParser
    grammar: src/main/resources/grammars/srgs/call.abnf
    converter: src/main/resources/grammars/cplanner/srgsconv
    tokenizer:
      class: de.dfki.mlt.rudimant.agent.nlp.TrivialTokenizer
      toLower: true           # turn all output to lower case
      removePunctuation: true  # remove all punctuation tokens

# ########## DEBUGGER/GUI SETTINGS ##########
debugPort: 9777

customCompileCommands:
  compile: ./compile
  mvncompile: mvn install
  mvncleancmp: mvn clean install
  vcompile: vondac -v -c config.yml
defaultCompileCommand: compile
