#!/bin/sh
scrdir=`dirname $0`
scrdir=`realpath $scrdir`

if test -f "logback.xml"; then
   logconf="-Dlogback.configurationFile=./logback.xml"
fi
java $logconf -jar "$scrdir"/target/mkm-jar-with-dependencies.jar "$@"
