#ABNF 1.0 UTF-8;

language de-DE;
root $top;
mode voice;
tag-format "semantics/1.0";

public $top = ($callRequest | $callConfirm) { out = $%1; };

$callsign = "$$.*";

$callRequest = (
  [das] $callsign { addr = "$$1"; } (für|an|von) $callsign { send = "$$1"; } [bitte] kommen
  )
  {
    out.da="Request"; out.prop="Call"; out.sender=send; out.addressee=addr;
  };

$callConfirm = (
  $callsign { send="$$1"; } hört [kommen] |
  [ja] ich { send="PRON1SG"; } höre [kommen] |
  $callsign { send="$$1"; } hier [kommen] |
  [ja] hier $callsign { send="$$1"; } [hört] [kommen]
  ) { out.da="Confirm"; out.prop="Call"; out.sender=send } ;
