#!/bin/sh
scdir=`dirname $0`
cd "$scdir"
container_id="rasa/rasa:3.6.20-full"
name="mkm_rasa_nlu"

if test -n "$name"; then
    name="--name $name"
fi

if test -z "$1"; then
    docker run -d --rm $name --user $UID:$UID -p 9797:5005 -v $(pwd):/app \
           "$container_id" run --enable-api --port 5005
else
    # e.g., for training
    gpus="--gpus all"
    docker run --rm --user $UID:$UID "$gpus" -v $PWD:/app "$container_id" "$@"
fi

#docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi

#docker run [-it] [--rm] --gpus all [-v $PWD:/tmp] gcr.io/rasa-platform/rasa:<tag> [rasa command]
